version: "3.9"

services:
  app:
    image: fmgornick/dynamic-proxy
    ports:
      - "${INTERNAL}:7777"
      - "${EXTERNAL}:8888"
    command: ["-dir", "${DIR}", "-xds", "envoy"]
    networks:
      - xds-network
    volumes:
      - ${PWD}/databags:/home/user/app/databags

  envoy:
    image: envoyproxy/envoy-dev
    networks:
      - xds-network
    volumes:
      - ${PWD}/bootstrap.yml:/etc/envoy/envoy.yaml
      - ${PWD}/certs:/etc/envoy/certs

networks:
  xds-network: { driver: bridge }
