version: "3.9"

services:
  app:
    image: fmgornick/dynamic-proxy
    ports:
      - "7777:7777"
      - "8888:8888"
      # - "6515:6515"
    command: ["-dir", "databags/dev", "-ia", "0.0.0.0", "-ea", "0.0.0.0"]
    volumes:
      - ${PWD}/databags:/home/user/app/databags

  envoy:
    image: envoyproxy/envoy-dev
    # ports:
    #   - "6515:6515"
    volumes:
      - ${PWD}/bootstrap.yml:/etc/envoy/envoy.yaml

volumes:
  databags: { external: false }
  bootstrap.yml: { external: false }
