version: "3.9"

services:
  app:
    container_name: app
    image: fmgornick/dynamic-proxy
    command: ["-dir", "${DIR}"]
    network_mode: host
    volumes:
      - ${PWD}/databags:/home/user/app/databags

  envoy:
    container_name: envoy
    image: envoyproxy/envoy-dev
    network_mode: host
    working_dir: /etc/envoy
    volumes:
      - ${PWD}/bootstrap.yml:/etc/envoy/envoy.yaml
      - ${PWD}/certs:/etc/envoy/certs
