version: "3.9"

services:
  proxy:
    container_name: proxy
    image: envoyproxy/envoy-dev
    ports:
      # ports envoy proxy will listen on
      - ${INTERNAL_PORT}:${INTERNAL_PORT}
      - ${EXTERNAL_PORT}:${EXTERNAL_PORT}
      # if add-http flag set, these will be the https ports
      - 48877:48877
      - 48878:48878
    working_dir: /etc/envoy
    volumes:
      - ${PWD}/bootstrap/docker.yml:/etc/envoy/envoy.yaml
      - ${PWD}/certs:/etc/envoy/certs
    depends_on: 
      - app

  app:
    container_name: app
    image: fmgornick/dynamic-proxy
    volumes:
      - ${PWD}/databags:/home/user/app/databags
    command: [
      "-add-http=${HTTP}",
      "-dir", "${DIR}",
      "-ia", "${INTERNAL_ADDRESS}",
      "-ip", "${INTERNAL_PORT}",
      "-icn", "${INTERNAL_CNAME}",
      "-ea", "${EXTERNAL_ADDRESS}",
      "-ep", "${EXTERNAL_PORT}",
      "-ecn", "${EXTERNAL_CNAME}",
    ]
